name: Build plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: |
          mkdir -p dist
          cp index.js manifest.json icon.svg README.md dist/
          cd dist && zip -r ../logseq-word-count-plugin.zip *
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: logseq-word-count-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
